---
functional:
  - Решение задачи на скорость против другого игрока.
  - Пользователь может сам создать игру, в которую можно играть с любым человеком, с ботом или другом (игра будет доступна по ссылке).
  - Оба игрока видят друг у друга редактор с кодом, вывод тестов.
  - Оба игрока могут менять язык программирования во время решения.
  - Можно выбрать игру по уровню сложности.
  - При создании игры можно выбрать определенную игру, иначе она будет подобрана наугад.
  - Задачи для решения даны на двух языках — русском и английском.
  - Другие пользователи могут следить за ходом игры.
  - В игре есть чат, в котором общаются зарегистрированные пользователи. Можно писать как отдельным пользователям, так и в общий чат. Сообщения можно писать на русском и английском языке.
  - Завершенная игра доступна в записи. Редактор для ввода кода выглядит как проигрыватель.
  - Пользователи получают очки, на основе которых строится рейтинг за неделю,
    месяц и за все время.
  - Пользователь может отменить созданную игру с другом
  - Игрок может в ходе игры сдаться, отменить действие, прервать игру досрочно, проиграть, победить.
  - Должна быть форма регистрации и авторизации пользователей.
 



non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован
    для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть удобным на мобильном устройстве.
  - Сайт должен быть протестирован на совместимость с последними версиями
    браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика (например,
    1000 одновременных пользователей).



implicit:
  - Количество игроков в одной игре не более 2.
  - Количество просматривающих игру в режиме online не ограничено.
  - В игре есть инструкция для пользователя.
  - Пользователь, который наблюдает за игрой двух игроков, не может вмешиваться в ход битвы.
