---
functional:
  - Решение задачи на скорость против другого игрока.
  - Оба игрока видят друг у друга редактор с кодом, вывод тестов.
  - Оба игрока могут менять язык программирования во время решения.
  - В игру можно играть с любым человеком, с ботом или другом (игра будет
    доступна по ссылке).
  - Можно выбрать игру по уровню сложности.
  - При создании игры можно выбрать определенную игру, иначе она будет подобрана
    наугад.
  - Задачи для решения даны на двух языках — русском и английском.
  - Другие пользователи могут следить за ходом игры.
  - В игре есть чат, в котором общаются зарегистрированные пользователи.
  - Завершенная игра доступна в записи. Редактор для ввода кода выглядит как
    проигрыватель.
  - Пользователи получают очки, на основе которых строится рейтинг за неделю,
    месяц и за все время.



non-functional:
  - Должна быть форма регистрации и авторизации пользователей.
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован
    для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть удобным на мобильном устройстве.
  - Сайт должен быть протестирован на совместимость с последними версиями
    браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика (например,
    1000 одновременных пользователей).



implicit:
  - Количество игроков в одной игре не более 2.
  - Количество просматривающих игру в режиме online не ограничено.
  - Возможность общаться в чате на русском и английском языке.
  - В игре есть инструкция для пользователя.
